import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";
import SmoothScroll from "@/components/SmoothScroll";
import CursorDot from "@/components/CursorDot";
import "./globals.css";

// Free, self-hostable typefaces (Google Fonts, OFL) standing in for the
// reference site's licensed TT Hoves. Swap here if a face is licensed later.
const display = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const mono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mono",
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const TITLE = "Meet Kapadia — Full-Stack Developer";
const DESCRIPTION =
  "Meet Kapadia — full-stack developer and CSE undergrad building products end to end. Based in Gujarat, India.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    // Case-study pages set their own full title; keep it as-is.
    template: "%s",
  },
  description: DESCRIPTION,
  applicationName: "Meet Kapadia",
  authors: [{ name: "Meet Kapadia" }],
  creator: "Meet Kapadia",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Meet Kapadia",
    title: TITLE,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter image is generated by app/twitter-image.tsx.
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${display.variable} ${mono.variable}`}>
      <body className="bg-black text-foreground antialiased">
        <CursorDot />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
