import type { Metadata, Viewport } from "next";
import { Space_Grotesk, Space_Mono, Instrument_Serif } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import SmoothScroll from "@/components/SmoothScroll";
import CursorDot from "@/components/CursorDot";
import CommandPalette from "@/components/CommandPalette";
import { getAllPosts } from "@/lib/mdx";
import RetroTerminal from "@/components/RetroTerminal";
import "./globals.css";
import dynamic from "next/dynamic";
import { cn } from "@/lib/utils";



const ShaderField = dynamic(() => import("@/components/ShaderField"), {
  ssr: false,
});

// Free, self-hostable typefaces (Google Fonts, OFL) standing in for the
// reference site's licensed TT Hoves. Swap here if a face is licensed later.
const display = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
});

const serif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
  display: "swap",
});

const mono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mono",
  display: "swap",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const TITLE = "Meet Kapadia — Full-Stack Developer";
const DESCRIPTION =
  "Meet Kapadia — full-stack developer and CSE undergrad building products end to end. Based in Gujarat, India.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    // Case-study pages set their own full title; keep it as-is.
    template: "%s",
  },
  description: DESCRIPTION,
  applicationName: "Meet Kapadia",
  authors: [{ name: "Meet Kapadia" }],
  creator: "Meet Kapadia",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Meet Kapadia",
    title: TITLE,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx (1200×630).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter image is generated by app/twitter-image.tsx.
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(display.variable, mono.variable, serif.variable, "font-sans")}>
      <body className="bg-background text-fg-primary antialiased relative">
        <div className="pointer-events-none fixed inset-0 z-[100] h-full w-full opacity-[0.03] mix-blend-overlay">
          <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" className="h-full w-full">
            <filter id="noiseFilter">
              <feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="3" stitchTiles="stitch" />
            </filter>
            <rect width="100%" height="100%" filter="url(#noiseFilter)" />
          </svg>
        </div>
        <ShaderField />
        <CursorDot />
        <CommandPalette blogPosts={getAllPosts().map(p => ({ title: p.meta.title, slug: p.meta.slug }))} />
        <div style={{ display: "none" }} dangerouslySetInnerHTML={{ __html: '<!-- try typing sudo -->' }} />
        <RetroTerminal />
        <SmoothScroll>{children}</SmoothScroll>
        <Analytics />
      </body>
    </html>
  );
}
